### ISSUE TITLE
Shader doesn't work in LWRP

### ISSUE THREAD

**Issue by antoson** [r3eckon/Unity-SimpleGrid-Shader#1]
Shader unsupported in Lightweight Render Pipeline.
Tried Unity's material convert, but no mapping exists.
Would love to use this asset in LWRP, if possible. Thanks!

**Comment by antoson** [comment]
**The Unlit shader works in LWRP.**
The bundled unitypackage does not contain the Unlit one,
sorry, didn't notice that.

**Comment by r3eckon** [comment]
Good to know that there are issues with the LWRP, I have not had a chance to test out the SRP with my shaders yet. Since Unlit works fine I'm assuming this is something to do with the lighting setup, although due to my limited knowledge of the render pipeline I could not say for sure. I'll take a look at this closer once I got the time.
